---
- name: deploy test war to jetty
  hosts: localhost
  become: true
  become_method: sudo
  
  tasks:
  - name: init jetty deploy folder
    file:
      path: ./jetty
      state: directory
      
  - name: copy file
    copy:
      src: ./../target/gs-rest-service-0.1.0.war
      dest: ./jetty/ROOT.war

  - name: start container
    docker_container:
      name: jetty_rest
      image: jetty:9.4.9
      ports:
      - 8087:8080
      volumes:
      - "/home/caozon/java_rest_example/ansible/jetty:/var/lib/jetty/webapps:Z"
      state: started
      recreate: yes
...